<?php

class SharedFilesAdminMaintenance {

  public function update_db_check() {

//    wp_clear_scheduled_hook('check_expired_files');

    if (!wp_next_scheduled('check_expired_files')) {
      wp_schedule_event(time(), 'daily', 'check_expired_files');
    }

    $sf_dir = wp_get_upload_dir()['basedir'] . '/shared-files/';
    $sf_file = $sf_dir . 'index.php';

    if (is_dir($sf_dir) && !file_exists($sf_file) && $file = fopen($sf_file, 'a')) {
      fwrite($file, '<?php // Automatically generated by Shared Files ?>' . PHP_EOL);
      fclose($file);
    }

  }

}
